
local rails_path = "__Bio_Industries__/graphics/entities/wood_products/rails/remnants/"

local rails_c_remnants = data.raw["rail-remnants"]["straight-rail-remnants-wood-bridge"]
rails_c_remnants.pictures.straight_rail_horizontal.stone_path_background.sheet.filename = rails_path ..  "remnants.png"
rails_c_remnants.pictures.straight_rail_horizontal.stone_path_background.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"
rails_c_remnants.pictures.straight_rail_vertical.stone_path_background.sheet.filename = rails_path ..  "remnants.png"
rails_c_remnants.pictures.straight_rail_vertical.stone_path_background.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"
rails_c_remnants.pictures.straight_rail_diagonal_left_top.stone_path_background.sheet.filename = rails_path ..  "remnants.png"
rails_c_remnants.pictures.straight_rail_diagonal_left_top.stone_path_background.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"
rails_c_remnants.pictures.straight_rail_diagonal_right_top.stone_path_background.sheet.filename = rails_path ..  "remnants.png"
rails_c_remnants.pictures.straight_rail_diagonal_right_top.stone_path_background.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"
rails_c_remnants.pictures.straight_rail_diagonal_right_bottom.stone_path_background.sheet.filename = rails_path ..  "remnants.png"
rails_c_remnants.pictures.straight_rail_diagonal_right_bottom.stone_path_background.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"
rails_c_remnants.pictures.straight_rail_diagonal_left_bottom.stone_path_background.sheet.filename = rails_path ..  "remnants.png"
rails_c_remnants.pictures.straight_rail_diagonal_left_bottom.stone_path_background.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"

rails_c_remnants.pictures.straight_rail_horizontal.stone_path.sheet.filename = rails_path ..  "remnants.png"
rails_c_remnants.pictures.straight_rail_horizontal.stone_path.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"
rails_c_remnants.pictures.straight_rail_vertical.stone_path.sheet.filename = rails_path ..  "remnants.png"
rails_c_remnants.pictures.straight_rail_vertical.stone_path.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"
rails_c_remnants.pictures.straight_rail_diagonal_left_top.stone_path.sheet.filename = rails_path ..  "remnants.png"
rails_c_remnants.pictures.straight_rail_diagonal_left_top.stone_path.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"
rails_c_remnants.pictures.straight_rail_diagonal_right_top.stone_path.sheet.filename = rails_path ..  "remnants.png"
rails_c_remnants.pictures.straight_rail_diagonal_right_top.stone_path.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"
rails_c_remnants.pictures.straight_rail_diagonal_right_bottom.stone_path.sheet.filename = rails_path ..  "remnants.png"
rails_c_remnants.pictures.straight_rail_diagonal_right_bottom.stone_path.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"
rails_c_remnants.pictures.straight_rail_diagonal_left_bottom.stone_path.sheet.filename = rails_path ..  "remnants.png"
rails_c_remnants.pictures.straight_rail_diagonal_left_bottom.stone_path.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"



local rails_curved_c_remnants = data.raw["rail-remnants"]["curved-rail-remnants-wood-bridge"]
rails_curved_c_remnants.pictures.curved_rail_vertical_left_top.stone_path_background.sheet.filename = rails_path ..  "remnants.png"
rails_curved_c_remnants.pictures.curved_rail_vertical_left_top.stone_path_background.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"
rails_curved_c_remnants.pictures.curved_rail_vertical_left_bottom.stone_path_background.sheet.filename = rails_path ..  "remnants.png"
rails_curved_c_remnants.pictures.curved_rail_vertical_left_bottom.stone_path_background.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"
rails_curved_c_remnants.pictures.curved_rail_vertical_right_top.stone_path_background.sheet.filename = rails_path ..  "remnants.png"
rails_curved_c_remnants.pictures.curved_rail_vertical_right_top.stone_path_background.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"
rails_curved_c_remnants.pictures.curved_rail_vertical_right_bottom.stone_path_background.sheet.filename = rails_path ..  "remnants.png"
rails_curved_c_remnants.pictures.curved_rail_vertical_right_bottom.stone_path_background.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"
rails_curved_c_remnants.pictures.curved_rail_horizontal_left_top.stone_path_background.sheet.filename = rails_path ..  "remnants.png"
rails_curved_c_remnants.pictures.curved_rail_horizontal_left_top.stone_path_background.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"
rails_curved_c_remnants.pictures.curved_rail_horizontal_right_top.stone_path_background.sheet.filename = rails_path ..  "remnants.png"
rails_curved_c_remnants.pictures.curved_rail_horizontal_right_top.stone_path_background.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"
rails_curved_c_remnants.pictures.curved_rail_horizontal_right_bottom.stone_path_background.sheet.filename = rails_path ..  "remnants.png"
rails_curved_c_remnants.pictures.curved_rail_horizontal_right_bottom.stone_path_background.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"
rails_curved_c_remnants.pictures.curved_rail_horizontal_left_bottom.stone_path_background.sheet.filename = rails_path ..  "remnants.png"
rails_curved_c_remnants.pictures.curved_rail_horizontal_left_bottom.stone_path_background.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"

rails_curved_c_remnants.pictures.curved_rail_vertical_left_top.stone_path.sheet.filename = rails_path ..  "remnants.png"
rails_curved_c_remnants.pictures.curved_rail_vertical_left_top.stone_path.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"
rails_curved_c_remnants.pictures.curved_rail_vertical_left_bottom.stone_path.sheet.filename = rails_path ..  "remnants.png"
rails_curved_c_remnants.pictures.curved_rail_vertical_left_bottom.stone_path.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"
rails_curved_c_remnants.pictures.curved_rail_vertical_right_top.stone_path.sheet.filename = rails_path ..  "remnants.png"
rails_curved_c_remnants.pictures.curved_rail_vertical_right_top.stone_path.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"
rails_curved_c_remnants.pictures.curved_rail_vertical_right_bottom.stone_path.sheet.filename = rails_path ..  "remnants.png"
rails_curved_c_remnants.pictures.curved_rail_vertical_right_bottom.stone_path.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"
rails_curved_c_remnants.pictures.curved_rail_horizontal_left_top.stone_path.sheet.filename = rails_path ..  "remnants.png"
rails_curved_c_remnants.pictures.curved_rail_horizontal_left_top.stone_path.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"
rails_curved_c_remnants.pictures.curved_rail_horizontal_right_top.stone_path.sheet.filename = rails_path ..  "remnants.png"
rails_curved_c_remnants.pictures.curved_rail_horizontal_right_top.stone_path.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"
rails_curved_c_remnants.pictures.curved_rail_horizontal_right_bottom.stone_path.sheet.filename = rails_path ..  "remnants.png"
rails_curved_c_remnants.pictures.curved_rail_horizontal_right_bottom.stone_path.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"
rails_curved_c_remnants.pictures.curved_rail_horizontal_left_bottom.stone_path.sheet.filename = rails_path ..  "remnants.png"
rails_curved_c_remnants.pictures.curved_rail_horizontal_left_bottom.stone_path.sheet.hr_version.filename = rails_path ..  "hr-remnants.png"

